// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Psidly.Shared.Data.Data;

#nullable disable

namespace Psidly.Shared.Data.Migrations
{
    [DbContext(typeof(PsidlyContext))]
    [Migration("20260503174623_AddAllTables")]
    partial class AddAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Psidly.Shared.Models.Models.Avaliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeOnly>("Hour")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hour");

                    b.Property<string>("ObsPaciente")
                        .HasColumnType("text")
                        .HasColumnName("obs_paciente");

                    b.Property<string>("ObsPsicologo")
                        .HasColumnType("text")
                        .HasColumnName("obs_psicologo");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.HasKey("Id")
                        .HasName("pk_avaliation");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_avaliation_patient_id");

                    b.ToTable("avaliation", (string)null);
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.AvaliationEmocao", b =>
                {
                    b.Property<int>("AvaliationId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliation_id");

                    b.Property<int>("EmocaoId")
                        .HasColumnType("integer")
                        .HasColumnName("emocao_id");

                    b.Property<int>("NivelEmocao")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_emocao");

                    b.HasKey("AvaliationId", "EmocaoId")
                        .HasName("pk_avaliation_emocao");

                    b.HasIndex("EmocaoId")
                        .HasDatabaseName("ix_avaliation_emocao_emocao_id");

                    b.ToTable("avaliation_emocao", (string)null);
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.Emocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_emocao");

                    b.ToTable("emocao", (string)null);
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Insurance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("insurance");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer")
                        .HasColumnName("psychologist_id");

                    b.HasKey("Id")
                        .HasName("pk_patient");

                    b.HasIndex("PsychologistId")
                        .HasDatabaseName("ix_patient_psychologist_id");

                    b.ToTable("patient", (string)null);
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.PsychologistInsurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("integer")
                        .HasColumnName("psychologist_id");

                    b.HasKey("Id")
                        .HasName("pk_convenio");

                    b.HasIndex("PsychologistId")
                        .HasDatabaseName("ix_convenio_psychologist_id");

                    b.ToTable("convenio", (string)null);
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Crp")
                        .HasColumnType("text")
                        .HasColumnName("crp");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ResetPasswordCode")
                        .HasColumnType("text")
                        .HasColumnName("reset_password_code");

                    b.Property<DateTime?>("ResetPasswordCodeExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reset_password_code_expiry");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.Avaliation", b =>
                {
                    b.HasOne("Psidly.Shared.Models.Models.Patient", "Patient")
                        .WithMany("Avaliations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliation_patient_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.AvaliationEmocao", b =>
                {
                    b.HasOne("Psidly.Shared.Models.Models.Avaliation", "Avaliation")
                        .WithMany("AvaliationEmocoes")
                        .HasForeignKey("AvaliationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliation_emocao_avaliation_avaliation_id");

                    b.HasOne("Psidly.Shared.Models.Models.Emocao", "Emocao")
                        .WithMany("AvaliationEmocoes")
                        .HasForeignKey("EmocaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliation_emocao_emocao_emocao_id");

                    b.Navigation("Avaliation");

                    b.Navigation("Emocao");
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.Patient", b =>
                {
                    b.HasOne("Psidly.Shared.Models.Models.User", "Psychologist")
                        .WithMany("Patients")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_user_psychologist_id");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.PsychologistInsurance", b =>
                {
                    b.HasOne("Psidly.Shared.Models.Models.User", "Psychologist")
                        .WithMany("Insurances")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_convenio_user_psychologist_id");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.Avaliation", b =>
                {
                    b.Navigation("AvaliationEmocoes");
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.Emocao", b =>
                {
                    b.Navigation("AvaliationEmocoes");
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.Patient", b =>
                {
                    b.Navigation("Avaliations");
                });

            modelBuilder.Entity("Psidly.Shared.Models.Models.User", b =>
                {
                    b.Navigation("Insurances");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
